name: saq
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy=1.22.4
    - scipy
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - seaborn
    - Cython<3.0
    - jax=0.3.25
    - jaxlib=0.3.25=*cuda*
    - cudatoolkit=11.8
    - cuda-nvcc=11.8
    - cudnn
    - pip:
        - chex==0.1.5
        - flax==0.6.0
        - optax==0.1.3
        - distrax==0.1.2
        - gym==0.23.1
        - absl-py
        - git+https://github.com/Farama-Foundation/D4RL.git@2b96431a0e9fd90c8032624b0dc3cd4514d15632
        - git+https://github.com/ARISE-Initiative/robomimic@dde3a6e74886e0768cedf18f8f9c813d47d31ebd
        - git+https://github.com/ARISE-Initiative/robosuite@de64fa5935f9f30ce01b36a3ef1a3242060b9cdb
        - wandb
        - ml_collections
        - tensorflow==2.12.0
        - tensorflow-probability==0.19.0
        - tensorflow-estimator==2.12.0
        - tensorboardX